import fs from "node:fs/promises";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { getTemplate, readVariableSchema, root, validateVariables } from "./library.mjs";

const [templateId, presetArg, formatArg = "mp4", outputBaseArg] = process.argv.slice(2);
if (!templateId) throw new Error("用法：npm run render -- <template-id> [preset.json] [mp4|webm] [输出文件名]");
const template = await getTemplate(templateId);
const format = ["mp4", "webm"].includes(formatArg) ? formatArg : "mp4";
const presetPath = presetArg ? path.resolve(root, presetArg) : path.join(template.absolutePath, "presets/default.json");
const values = JSON.parse(await fs.readFile(presetPath, "utf8"));
const schema = await readVariableSchema(template.absolutePath);
validateVariables(schema, values);
const renderValues = schema.some((item) => item.id === "exportMode") ? { ...values, exportMode: format === "mp4" ? "mp4" : "transparent" } : values;
const outputDir = path.join(root, "renders", templateId);
await fs.mkdir(outputDir, { recursive: true });
const outputBase = outputBaseArg || path.basename(presetPath, ".json");
const output = path.join(outputDir, `${outputBase}.${format}`);
const result = spawnSync("npx", ["--yes", "hyperframes@0.6.115", "render", "--format", format, "--strict-variables", "--variables", JSON.stringify(renderValues), "--output", output], { cwd: template.absolutePath, stdio: "inherit" });
process.exit(result.status || 0);
