import fs from "node:fs/promises";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { getTemplate, readVariableSchema, root, validateVariables } from "./library.mjs";

const [templateId, presetArg] = process.argv.slice(2);
if (!templateId) throw new Error("用法：npm run render -- <template-id> [preset.json]");
const template = await getTemplate(templateId);
const presetPath = presetArg ? path.resolve(root, presetArg) : path.join(template.absolutePath, "presets/default.json");
const values = JSON.parse(await fs.readFile(presetPath, "utf8"));
const schema = await readVariableSchema(template.absolutePath);
validateVariables(schema, values);
const renderValues = schema.some((item) => item.id === "exportMode") ? { ...values, exportMode: "mp4" } : values;
const outputDir = path.join(root, "renders", templateId);
await fs.mkdir(outputDir, { recursive: true });
const output = path.join(outputDir, `${path.basename(presetPath, ".json")}.mp4`);
const renderVariablesPath = path.join(outputDir, `.${path.basename(presetPath, ".json")}.render-vars.json`);
await fs.writeFile(renderVariablesPath, JSON.stringify(renderValues), "utf8");
const renderArgs = ["--yes", "hyperframes@0.6.115", "render", "--workers", "3", "--strict-variables", "--variables-file", renderVariablesPath, "--output", output];
const npxCli = path.join(path.dirname(process.execPath), "node_modules", "npm", "bin", "npx-cli.js");
const command = process.platform === "win32" ? process.execPath : "npx";
const commandArgs = process.platform === "win32" ? [npxCli, ...renderArgs] : renderArgs;
const result = spawnSync(command, commandArgs, { cwd: template.absolutePath, stdio: "inherit" });
await fs.rm(renderVariablesPath, { force: true });
if (result.error) throw result.error;
process.exit(result.status ?? 1);
